GET http://localhost:3000/api/v1/tasks

###

POST http://localhost:3000/api/v1/tasks
Content-Type: application/json

{
    "title": "task 1" 
}

###
# @prompt id
DELETE http://localhost:3000/api/v1/tasks/{{id}}