GET http://localhost:3000/api/v1/tasks

###
# @prompt title
POST http://localhost:3000/api/v1/tasks
Content-Type: application/json

{
    "title": "{{title}}"
}

###
# @prompt id
DELETE http://localhost:3000/api/v1/tasks/{{id}}